project_id = "xgurpabsifgxeyqjlwxu"

[functions.process-daily-accruals]
verify_jwt = false

[functions.test-afas-connection]
verify_jwt = false

[functions.get-afas-schema]
verify_jwt = false

[functions.test-afas-read]
verify_jwt = false

[functions.test-afas-write]
verify_jwt = false
